before_script:
 - echo "Fetching packer"
 - wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
 - unzip packer_1.7.8_linux_amd64.zip
 - chmod +x packer
 

stages:
 - test
 - deploy

test-job:
 stage: test
 script:
 - echo "Validating Packer template"
 - ./packer validate ./AMIcode.json

deploy-job:
 stage: deploy
 
 script:
 - echo "Creating AMI image..."
 - ./packer build -var login_username=$AWS_ACCESS_KEY_ID -var login_password=$AWS_SECRET_ACCESS_KEY ./AMIcode.json
 - echo "AMI image successfully published1."
